// SNG $POKER emission curve — TS twin of programs/fastpoker/src/emission.rs
// Keep in lockstep with the Rust version. Returns 6-dec unrefined micro-units
// (display divides by 1e6; on-chain claim multiplies by 1000 for 9-dec SPL).

export enum EmissionFormat {
  HU = 0,
  Six = 1,
  Nine = 2,
  Cash = 3,
}

export const BASE_HU_UNREFINED = BigInt(40 * 1_000_000);
export const BASE_6MAX_UNREFINED = BigInt(120 * 1_000_000);
export const BASE_9MAX_UNREFINED = BigInt(180 * 1_000_000);
export const DEFAULT_SNG_EMISSION_TIER = 3; // Gold
export const TIER_EMISSION_FACTOR_BPS = [
  1_000,   // Copper: 0.1x
  2_000,   // Bronze: 0.2x
  5_000,   // Silver: 0.5x
  10_000,  // Gold: 1.0x
  20_000,  // Platinum: 2.0x
  40_000,  // Diamond: 4.0x
  100_000, // Black: 10.0x
] as const;
export const FLOOR_BPS = BigInt(500);
const ONE_WHOLE_POKER_BASE = BigInt(1_000_000_000);
const WHOLE_POKER_PER_BUCKET = BigInt(10_000_000);
const TEN_THOUSAND = BigInt(10000);
const ZERO = BigInt(0);

// bucket[i] = round((1 - i/100)^1.2 * 10000). Generated by scripts/gen_decay_table.py.
export const DECAY_TABLE_BPS: number[] = [
  10000, 9880, 9760, 9641, 9522, 9403, 9284, 9166, 9048, 8930,
   8812, 8695, 8578, 8461, 8344, 8228, 8112, 7996, 7881, 7766,
   7651, 7536, 7422, 7308, 7194, 7081, 6968, 6855, 6742, 6630,
   6518, 6406, 6295, 6184, 6074, 5963, 5854, 5744, 5635, 5526,
   5417, 5309, 5201, 5094, 4987, 4880, 4774, 4668, 4563, 4457,
   4353, 4248, 4145, 4041, 3938, 3836, 3734, 3632, 3531, 3430,
   3330, 3231, 3131, 3033, 2935, 2837, 2740, 2644, 2548, 2453,
   2358, 2264, 2171, 2078, 1986, 1895, 1804, 1714, 1625, 1537,
   1450, 1363, 1277, 1193, 1109, 1026,  945,  864,  785,  707,
    631,  556,  483,  411,  342,  275,  210,  149,   91,   40,
];

export function decayMultiplierBps(netCircBaseUnits: bigint): number {
  const netCircWhole = netCircBaseUnits / ONE_WHOLE_POKER_BASE;
  const bucket = Number(netCircWhole / WHOLE_POKER_PER_BUCKET);
  if (bucket >= 99) return DECAY_TABLE_BPS[99];
  const lo = BigInt(DECAY_TABLE_BPS[bucket]);
  const hi = BigInt(DECAY_TABLE_BPS[bucket + 1]);
  const frac = netCircWhole % WHOLE_POKER_PER_BUCKET;
  const drop = lo - hi;
  const interp = (drop * frac) / WHOLE_POKER_PER_BUCKET;
  return Number(lo - interp);
}

export function calculateSngEmissionPerSeat(
  format: EmissionFormat,
  netCircBaseUnits: bigint,
  tier = DEFAULT_SNG_EMISSION_TIER,
): bigint {
  let base: bigint;
  switch (format) {
    case EmissionFormat.HU: base = BASE_HU_UNREFINED; break;
    case EmissionFormat.Six: base = BASE_6MAX_UNREFINED; break;
    case EmissionFormat.Nine: base = BASE_9MAX_UNREFINED; break;
    default: return ZERO;
  }
  const tierFactorBps = BigInt(
    TIER_EMISSION_FACTOR_BPS[tier] ?? TIER_EMISSION_FACTOR_BPS[DEFAULT_SNG_EMISSION_TIER],
  );
  const tierScaledBase = (base * tierFactorBps) / TEN_THOUSAND;
  const decayBps = BigInt(decayMultiplierBps(netCircBaseUnits));
  const curve = (tierScaledBase * decayBps) / TEN_THOUSAND;
  const floor = (tierScaledBase * FLOOR_BPS) / TEN_THOUSAND;
  return curve > floor ? curve : floor;
}

export function calculateSngPoolUnrefined(
  format: EmissionFormat,
  maxPlayers: number,
  netCircBaseUnits: bigint,
  tier = DEFAULT_SNG_EMISSION_TIER,
): bigint {
  return calculateSngEmissionPerSeat(format, netCircBaseUnits, tier) * BigInt(maxPlayers);
}

/**
 * 10% of every SNG's gross emission feeds the Royal Jackpot pool. Mirror
 * of the contract's `GRAND_FUNDING_BPS = 1000` constant in
 * `programs/fastpoker/src/state/jackpot.rs`.
 */
export const ROYAL_FUNDING_BPS = 1000n;

export interface EmissionSplit {
  /** Total emission before the Royal Jackpot skim. */
  gross: bigint;
  /** Royal Jackpot share (10% of gross). */
  royalSkim: bigint;
  /** Player pool, distributed to finishers via PokerPayoutStructure. */
  playerPool: bigint;
}

/**
 * Split a gross SNG emission into its Royal Jackpot skim and player-pool
 * portions. Use this everywhere the UI needs to attribute emissions to
 * the three legs of the flywheel (raw yield, jackpot, player payouts).
 */
export function splitGrossEmission(gross: bigint): EmissionSplit {
  const royalSkim = (gross * ROYAL_FUNDING_BPS) / TEN_THOUSAND;
  const playerPool = gross - royalSkim;
  return { gross, royalSkim, playerPool };
}
